// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTlR67TdFeMHNqwlRng_8H3-A953ty4s',
    appId: '1:260790033662:web:ef39b2ad557561d3dc19af',
    messagingSenderId: '260790033662',
    projectId: 'vitaville-d30a7',
    authDomain: 'vitaville-d30a7.firebaseapp.com',
    storageBucket: 'vitaville-d30a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEVcdEmjLPoyOQjfdhf8LdJjn5qksX350',
    appId: '1:260790033662:android:3129a07121cd8a68dc19af',
    messagingSenderId: '260790033662',
    projectId: 'vitaville-d30a7',
    storageBucket: 'vitaville-d30a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Xk5JzDL0UEISXcDK76XN4cA64o3b0wo',
    appId: '1:260790033662:ios:cfff18e29f5f128fdc19af',
    messagingSenderId: '260790033662',
    projectId: 'vitaville-d30a7',
    storageBucket: 'vitaville-d30a7.appspot.com',
    iosClientId: '260790033662-b9l2opebt3su73v7ku284ahqakukn4es.apps.googleusercontent.com',
    iosBundleId: 'fr.vitaville.vitaville',
  );
}